### ISSUE TITLE
Lyrics Endpoint

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/dhravyaAPI#10]
I tried a lot of lyrics stuff but could never get a good lyrics provider that is also free

Genius was an option that I used in spacebot, but it is no longer possible to use bots on their website
I also tried [the lyrics extractor library](https://pypi.org/project/lyrics-extractor/) it worked for the most part after removing genius, but lyrics were still not available for most songs, not even popular ones 💀 

I was really frustrated at this point and thought, "Fuck it, no point in making a lyrics api"

But you're the master who can pull internal apis and stuff, any more ideas/apis that can help with this?

**Comment by Dhravya** [comment]
possible?

**Comment by Dhravya** [comment]
yo @itsnotrin let me know how you'll be doing it

**Comment by itsnotrin** [comment]
I coded a lyrics command a while ago in JS. Just tested it and it still works, I'll read my src from that and port it over to PY

**Comment by Dhravya** [comment]
Amazing then! People really want and need the lyrics endpoint haha

**Comment by Dhravya** [comment]
yo @itsnotrin can this be done within the next 3 days?

**Comment by itsnotrin** [comment]
I can try

**Comment by PolyAnthi** [comment]
I've sorted this, also added a ?simple option which formats the lyrics too
