### ISSUE TITLE
Use of flask

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/dhravyaAPI#2]
Many users of the api informed me that using Flask is a bad idea and that fast api is much better

which it is, but the issue is, i dont know anything about fastapi right now lol

**Comment by itsnotrin** [comment]
I did a few small FastAPI projects, I'll make a branch and start work on it

**Comment by itsnotrin** [comment]
https://stackoverflow.com/questions/68181782/how-to-run-fastapi-on-apache2

Follow this for routing it through to apache.

**Comment by Dhravya** [comment]
Alright, I'll be doing it when the rewrite is done

**Comment by Dhravya** [comment]
Pretty much done, but in testing phase
