### ISSUE TITLE
Using file names from root

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/dhravyaAPI#4]
Its just bad. 
I have been trying to fix this linux issue since a long time and just resorted to using the entire path of the file 
`/var/www/api/dhravyaAPI/qrcodes`
Instead of `/qrcodes`

No idea how to fix, since i'm a noob with linux

**Comment by itsnotrin** [comment]
Could try `./` ?

**Comment by Dhravya** [comment]
i tried, didn't work

seems like the root is different, but idk what it is

**Comment by itsnotrin** [comment]
In python there is cwd

import os
os.cwd() # Not sure if you need the brackets

Instead of having to type out the /var/www etc etc, it automatically goes to the directory you're currently in. We should use that instead of hard coding paths

**Comment by Dhravya** [comment]
Thanks, I think this is fixed, but not tested yet
