### ISSUE TITLE
Fetching memes is slow - probably will fix itself after fastAPI

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/dhravyaAPI#6]
RIght now, the `api.dhravya.me/meme` endpoint is good, but **slow** like super slow

I did everything in my knowledge to make it fast, but since its downloading the image from reddit and THEN sending it, i guess its bound to happen
currently, its s a streaming response which i dont think it exists in fastAPI

**Comment by itsnotrin** [comment]
We could just forward the i.reddit.com response straight to discord instead of downloading & returning it like that

**Comment by Dhravya** [comment]
nah, the idea was the people could use the api in thier GitHub READMES and not have to parse/download anything

like for example in my Readme

**Comment by itsnotrin** [comment]
That would still work fine, it's still an image being returned all the same

**Comment by Dhravya** [comment]
Fixed- I made a streaming response along with io.byteio instead of downloading the files, works perfectly and returns a response within 0.76 seconds
